_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 1023
compile:
    value: false
dataset:
    value: hf_dataset_stockfish
decay_lr:
    value: true
device:
    value: cuda:1
dropout:
    value: 0
dtype:
    value: bfloat16
eval_interval:
    value: 4000
eval_iters:
    value: 100
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 4
init_from:
    value: scratch
learning_rate:
    value: 0.0003
log_interval:
    value: 50
lr_decay_iters:
    value: 600000
max_iters:
    value: 600000
min_lr:
    value: 3e-05
n_embd:
    value: 768
n_head:
    value: 8
n_layer:
    value: 16
out_dir:
    value: out-stockfish_xl
wandb_log:
    value: true
wandb_project:
    value: chess-gpt
wandb_run_name:
    value: layer_16_block_1023_batch_32_dataset_hf_dataset_stockfish
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
